defmodule Lyskom.ProtA.Async do
  def async(0), do: :async_new_text_old
  def async(1), do: :async_i_am_off
  def async(2), do: :async_i_am_on_obsolete
  def async(5), do: :async_new_name
  def async(6), do: :async_i_am_on
  def async(7), do: :async_sync_db
  def async(8), do: :async_leave_conf
  def async(9), do: :async_login
  def async(10), do: :async_broadcast
  def async(11), do: :async_rejected_connection
  def async(12), do: :async_send_message
  def async(13), do: :async_logout
  def async(14), do: :async_deleted_text
  def async(15), do: :async_new_text
  def async(16), do: :async_new_recipient
  def async(17), do: :async_sub_recipient
  def async(18), do: :async_new_membership
  def async(19), do: :async_new_user_area
  def async(20), do: :async_new_presentation
  def async(21), do: :async_new_motd
  def async(22), do: :async_text_aux_changed
  def async('0'), do: :async_new_text_old
  def async('1'), do: :async_i_am_off
  def async('2'), do: :async_i_am_on_obsolete
  def async('5'), do: :async_new_name
  def async('6'), do: :async_i_am_on
  def async('7'), do: :async_sync_db
  def async('8'), do: :async_leave_conf
  def async('9'), do: :async_login
  def async('10'), do: :async_broadcast
  def async('11'), do: :async_rejected_connection
  def async('12'), do: :async_send_message
  def async('13'), do: :async_logout
  def async('14'), do: :async_deleted_text
  def async('15'), do: :async_new_text
  def async('16'), do: :async_new_recipient
  def async('17'), do: :async_sub_recipient
  def async('18'), do: :async_new_membership
  def async('19'), do: :async_new_user_area
  def async('20'), do: :async_new_presentation
  def async('21'), do: :async_new_motd
  def async('22'), do: :async_text_aux_changed
end
